plugins {
    id 'java-library'
    id("com.gradleup.shadow") version "9.0.2"
    id 'org.jetbrains.kotlin.jvm' version '2.4.0'
    id "org.jetbrains.kotlin.plugin.spring" version '2.4.0'
}

group = 'dev.dnpm'
version = '0.2.0' // x-release-please-version
description = 'ZPM Dashbord UKGM'

java.sourceCompatibility = JavaVersion.VERSION_11

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

repositories {
    mavenCentral()
}

ext {
    onkostarVersion = '2.14.0'
    springVersion = '4.3.8.RELEASE'
    slf4jVersion = '1.7.2'
    junit4Version = '4.13.2'
    junitVersion = '5.14.3'
    junitPlatformVersion = '1.14.3'
    assertjVersion = '3.27.7'
    mockitoVersion = '5.23.0'
}

dependencies {
    compileOnly files("./libs/onkostar-api-${onkostarVersion}.jar")

    compileOnly "org.springframework:spring-beans:${springVersion}"
    compileOnly "org.springframework:spring-context:${springVersion}"
    compileOnly "org.springframework:spring-webmvc:${springVersion}"
    compileOnly "org.springframework:spring-jdbc:${springVersion}"
    compileOnly "org.slf4j:slf4j-api:${slf4jVersion}"
    compileOnly "org.apache.poi:poi-ooxml:5.2.0"

    implementation "org.jetbrains.kotlin:kotlin-stdlib"

    testImplementation "org.springframework:spring-test:${springVersion}"
    testImplementation "org.springframework:spring-context:${springVersion}"
    testImplementation "org.springframework:spring-jdbc:${springVersion}"
    testImplementation "com.h2database:h2:2.4.240"
    testImplementation "junit:junit:${junit4Version}"
    testImplementation "org.junit.vintage:junit-vintage-engine:${junitVersion}"
    testImplementation "org.junit.jupiter:junit-jupiter-params:${junitVersion}"
    testImplementation "org.junit.platform:junit-platform-launcher:${junitPlatformVersion}"
    testImplementation "org.assertj:assertj-core:${assertjVersion}"
    testImplementation "org.mockito:mockito-core:${mockitoVersion}"
    testImplementation "org.mockito:mockito-junit-jupiter:${mockitoVersion}"
    testImplementation "ca.uhn.hapi:hapi-structures-v26:2.3"
    testImplementation "org.hibernate:hibernate-core:4.3.11.Final"
}

tasks.jar {
    enabled = false
}

tasks.assemble {
    dependsOn(tasks.shadowJar)
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.shadowJar {
    archiveClassifier.set("")
    minimize()
    relocate("kotlin", "dev.dnpm.zpmdashboard.vendor.kotlin")
    relocate("org.jetbrains", "dev.dnpm.zpmdashboard.vendor.org.jetbrains")
}

build.dependsOn shadowJar
